sudo: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - DJANGO_SETTINGS_MODULE=settings
  matrix:
    - DJANGO="Django<2.3"  # Django 2.2
    - DJANGO="Django<3.1"  # Django 3.0
    - DJANGO="Django<3.2"  # Django 3.1
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pipenv
  - pipenv install $DJANGO
  - pipenv install .
  - pipenv install --dev six pytest pytest-django pytest-selenium selenium
script:
  - pipenv run python setup.py test
