name: build

on:
  - push
  - pull_request

jobs:
  test:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6]
        django: [<2.3]
#        python: [3.6, 3.7, 3.8, 3.9]
#        django: [<2.3, <3.1, <3.2]
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt install -y tree google-chrome-stable firefox  # not required
          pip install wheel
          pip install "Django${{ matrix.django }}"
          pip install .
          pip install six pytest pytest-django pytest-seleniumbase
          seleniumbase install chromedriver
          seleniumbase install geckodriver
      - name: Test
        run: |
          pwd
          tree
          DJANGO_SETTINGS_MODULE=test_proj.settings pytest tests/ --browser=${{ matrix.browser }} --headless
